import { ComparisonPage, type ComparisonPageConfig } from "../components/ComparisonPage";
import { createMarketingMetadata } from "../lib/metadata";

export const metadata = createMarketingMetadata({ title: "Checkfront Alternative - Booking Software Comparison", description: "Compare Checkfront and ReservKit for pricing, booking types, Stripe payments, waivers, inventory, distribution, and direct-booking operations.", keywords: ["Checkfront alternative", "Checkfront competitor", "rental booking software comparison"], path: "/checkfront-alternative" });
const config: ComparisonPageConfig = {
  platform: "Checkfront", eyebrow: "Checkfront alternative", title: "ReservKit vs. Checkfront: compare flexibility, distribution, and operating fit", intro: "Checkfront emphasizes flexible booking types, resource management, distribution, and one broad product plan. ReservKit offers tiered public pricing and a direct-booking workflow built around Stripe, waivers, deposits, equipment, and the operating day.", updated: "October 9, 2026", sourceUrl: "https://www.checkfront.com/pricing/", sourceLabel: "Checkfront's official pricing page",
  competitorStrengths: ["Daily, multi-day, hourly, timeslot, and flexible booking models", "Checkfront's established resource-management and OTA distribution toolset", "Built-in waivers and a broad all-in-one plan", "Published monthly-plus-booking-fee pricing with a guest pass-through option"], reservkitStrengths: ["Three self-serve tiers that reduce the booking-fee rate as the operator grows", "A Pro booking-fee cap for higher-volume direct sales", "Stripe Connect, refund policy, deposits, waivers, and named units documented as one money-and-operations flow", "Guided migration and public operator documentation before purchase"],
  chooseCompetitorIf: ["You need its wider set of booking types or established OTA connections now.", "A single broad feature plan is preferable to tiered feature gates.", "Its resource and distribution ecosystem matches your current operation."], chooseReservKitIf: ["You prefer a lower booking-fee rate at Growth or Pro volume.", "You want operator-owned Stripe connectivity and explicit refund-fee rules.", "Your core flow is timed tours, activities, charters, or rentals with waivers, deposits, or equipment.", "You want a full-access trial before selecting a tier."],
  checkpoints: [{ title: "Model the booking type", body: "Confirm the system represents the real duration, start-time, resource, and capacity rules." }, { title: "Compare total cost", body: "Use the same monthly booked subtotal and include subscription, software fee, and payment processing." }, { title: "Check distribution", body: "Name every OTA or reseller connection that produces meaningful bookings today." }, { title: "Test exceptions", body: "Cancel, refund, reschedule, release equipment, and verify all customer messages." }],
  faqs: [{ title: "How is ReservKit pricing different from Checkfront?", body: "ReservKit publishes Starter, Growth, and Pro tiers with decreasing booking-fee rates. Checkfront currently describes one plan with a monthly subscription and a 3% online booking fee. Verify current Checkfront terms directly." }, { title: "Does ReservKit support every Checkfront booking type?", body: "No. ReservKit is strongest for scheduled tours, activities, charters, and timed rentals. Operators needing nightly accommodation or unusually flexible multi-day inventory should validate fit carefully." }, { title: "Can ReservKit pass its booking fee to guests?", body: "ReservKit does not add its booking fee as a separate checkout surcharge. Operators may configure their own customer-facing service fees where permitted and are responsible for applicable disclosure and law." }],
};
export default function CheckfrontAlternative() { return <ComparisonPage config={config} />; }
