import { ComparisonPage, type ComparisonPageConfig } from "../components/ComparisonPage";
import { createMarketingMetadata } from "../lib/metadata";

export const metadata = createMarketingMetadata({ title: "FareHarbor Alternative - Transparent Booking Software", description: "Compare FareHarbor and ReservKit for public pricing, direct bookings, Stripe payments, waivers, equipment, migration, and day-of operations.", keywords: ["FareHarbor alternative", "FareHarbor competitor", "booking software like FareHarbor"], path: "/fareharbor-alternative" });

const config: ComparisonPageConfig = {
  platform: "FareHarbor", eyebrow: "FareHarbor alternative", title: "ReservKit vs. FareHarbor: choose on control, support, and the booking flow", intro: "FareHarbor is a large, established platform with extensive support and distribution. ReservKit is a focused alternative for operators who value published pricing, their own Stripe relationship, integrated operational records, and a guided first migration.", updated: "October 9, 2026", sourceUrl: "https://fareharbor.com/solutions/tours/", sourceLabel: "FareHarbor's tour-operator overview",
  competitorStrengths: ["A mature platform used by a large number of tour and activity businesses", "24/7 support and a broad implementation organization", "Hundreds of OTA connections and a large distribution footprint", "Deep feature coverage for established tourism operations"],
  reservkitStrengths: ["Public plan prices and booking-fee percentages before a sales call", "Stripe Connect payments tied to the operator's connected Stripe account", "Waiver evidence, refundable deposits, equipment demand, staff context, and check-in tied to the booking", "A 14-day full-access trial and a migration path built around proving one complete booking flow"],
  chooseCompetitorIf: ["You prioritize a large support organization and broad OTA distribution today.", "You need an incumbent platform with a long operating history and a large customer base.", "Your rollout depends on integrations ReservKit does not currently claim."],
  chooseReservKitIf: ["You want to know the software price before speaking with sales.", "You prefer a direct Stripe Connect payment relationship and a focused operator workspace.", "Waivers, deposits, named equipment units, and day-of readiness are central to the operation.", "You want to test the complete booking path before moving live traffic."],
  checkpoints: [{ title: "Rebuild one activity", body: "Match duration, capacity, cutoffs, price, location, and every start time." }, { title: "Test mobile checkout", body: "Use a real phone and complete guest details, payment, confirmation, and waiver entry." }, { title: "Compare money movement", body: "Write down processing fees, software fees, refund behavior, payout ownership, and dispute responsibility." }, { title: "Run the operating day", body: "Verify check-in, staff visibility, equipment readiness, balances, and customer messages." }],
  faqs: [{ title: "Is ReservKit a complete FareHarbor replacement for every operator?", body: "No. FareHarbor has broader distribution reach, a larger support organization, and a longer integration history. ReservKit should be evaluated against the exact booking, payment, waiver, equipment, and staff workflows your business needs now." }, { title: "Does ReservKit publish its pricing?", body: "Yes. Starter, Growth, and Pro pricing and booking fees are published on the ReservKit pricing page, with custom terms for Enterprise." }, { title: "Can I migrate without changing everything at once?", body: "Yes. The recommended path is to configure one activity, connect Stripe, recreate availability and requirements, complete a controlled booking, and only then move customer traffic." }],
};

export default function FareHarborAlternative() { return <ComparisonPage config={config} />; }
