import { ComparisonPage, type ComparisonPageConfig } from "../components/ComparisonPage";
import { createMarketingMetadata } from "../lib/metadata";

export const metadata = createMarketingMetadata({ title: "Peek Pro Alternative - Booking Software Comparison", description: "Compare Peek Pro and ReservKit for booking, pricing, Stripe payments, automation, mobile operations, waivers, resources, and migration.", keywords: ["Peek Pro alternative", "Peek Pro competitor", "tour booking software comparison"], path: "/peek-pro-alternative" });
const config: ComparisonPageConfig = {
  platform: "Peek Pro", eyebrow: "Peek Pro alternative", title: "ReservKit vs. Peek Pro: compare automation depth with focused operator control", intro: "Peek Pro positions itself as an AI operating system with conversion, marketing, automation, native mobile, and connectivity tools. ReservKit focuses on a transparent direct-booking stack that smaller rental and experience operators can configure, prove, and run.", updated: "October 9, 2026", sourceUrl: "https://www.peekpro.com/", sourceLabel: "Peek Pro's official product overview",
  competitorStrengths: ["AI-assisted revenue, marketing, and operational automation", "Native mobile apps, point-of-sale, and a broad connectivity ecosystem", "Abandoned-cart recovery, waitlists, dynamic pricing, and guest lifecycle tools", "Established customer stories and a larger market footprint"],
  reservkitStrengths: ["Published monthly pricing and booking fees", "Operator-connected Stripe checkout with explicit fee and refund documentation", "Core booking, waiver, deposit, equipment, staff, and check-in records in one workflow", "A smaller, guided implementation surface for operators who do not need an enterprise automation stack"],
  chooseCompetitorIf: ["AI automation, cart recovery, native apps, and broad integrations are immediate requirements.", "You need a mature point-of-sale and marketing ecosystem.", "You are prepared for a sales-led evaluation of a larger platform."], chooseReservKitIf: ["You need direct booking fundamentals and operational clarity before advanced automation.", "Transparent pricing and Stripe ownership matter more than ecosystem breadth.", "You want integrated waivers, refundable deposits, and named equipment-unit blocking.", "You prefer to prove one live flow during a full-access trial."],
  checkpoints: [{ title: "Measure conversion", body: "Compare the same activity, phone, traffic source, and checkout requirements." }, { title: "List required automation", body: "Separate must-have reminders and follow-up from attractive features your team will not operate yet." }, { title: "Price the full stack", body: "Include software, booking, payment, messaging, add-on, and implementation costs." }, { title: "Test staff adoption", body: "Have the people running check-in and dispatch complete their real daily tasks." }],
  faqs: [{ title: "Does ReservKit have every Peek Pro automation?", body: "No. Peek Pro advertises a broader AI, marketing, point-of-sale, mobile-app, and integration ecosystem. ReservKit's launch offer is narrower and centered on direct booking and operations." }, { title: "Does ReservKit support dynamic pricing?", body: "Yes. Dynamic pricing is available on Growth and higher plans, alongside coupons, add-ons, waivers, reports, equipment, and deposits." }, { title: "Which is easier to evaluate without a sales call?", body: "ReservKit publishes its self-serve plan prices and offers a 14-day full-access trial. Operators should still test both products against their own workflow." }],
};
export default function PeekProAlternative() { return <ComparisonPage config={config} />; }
