export const MARKETING_ROUTES = [
  "/",
  "/pricing",
  "/early-access",
  "/docs",
  "/docs/getting-started",
  "/docs/faq",
  "/docs/activities",
  "/docs/daily-operations",
  "/docs/customers-guest-hub",
  "/docs/payments",
  "/docs/staff",
  "/docs/waivers",
  "/docs/notifications",
  "/docs/reports",
  "/docs/bookings-availability",
  "/docs/equipment",
  "/docs/growth-tools",
  "/docs/settings-migration",
  "/roadmap",
  "/changelog",
  "/blog",
  "/compare",
  "/fareharbor-alternative",
  "/peek-pro-alternative",
  "/checkfront-alternative",
  "/rezdy-alternative",
  "/equipment-rental-booking-software",
  "/activity-booking-software",
  "/atv-rental-booking-software",
  "/bike-rental-booking-software",
  "/escape-room-booking-software",
  "/fishing-charter-booking-software",
  "/boat-rental-software",
  "/kayak-rental-software",
  "/watersports-rental-software",
  "/jet-ski-rental-software",
  "/rental-booking-software-with-waivers",
  "/rental-booking-software-with-damage-deposits",
  "/stripe-booking-software-for-rentals",
  "/switch-rental-booking-software",
  "/tour-operator-software",
  "/terms",
  "/privacy",
];

export const MARKETING_REDIRECT_ROUTES = ["/beta"];

export const EXPECTED_REDIRECTS = {
  "/beta": "/early-access",
};
