import { ComparisonPage, type ComparisonPageConfig } from "../components/ComparisonPage";
import { createMarketingMetadata } from "../lib/metadata";

export const metadata = createMarketingMetadata({ title: "Rezdy Alternative - Tour Booking Software Comparison", description: "Compare Rezdy and ReservKit for tour bookings, distribution, pricing, Stripe payments, waivers, resources, reports, and migration.", keywords: ["Rezdy alternative", "Rezdy competitor", "tour operator software comparison"], path: "/rezdy-alternative" });
const config: ComparisonPageConfig = {
  platform: "Rezdy", eyebrow: "Rezdy alternative", title: "ReservKit vs. Rezdy: compare distribution reach with direct-booking control", intro: "Rezdy combines booking software with a large reseller and OTA distribution network. ReservKit is a direct-booking alternative for operators prioritizing transparent pricing, Stripe Connect, waivers, deposits, equipment, and clear day-of execution.", updated: "October 9, 2026", sourceUrl: "https://rezdy.com/tours/", sourceLabel: "Rezdy's official tour-operator page",
  competitorStrengths: ["A large reseller and channel-manager network", "Established tools for tours, activities, guest manifests, and resources", "Gift cards, vouchers, packages, extras, and broader distribution options", "Published plan structure and a 21-day trial"], reservkitStrengths: ["Lower published booking-fee rates on current Growth and Pro plans", "Stripe Connect checkout and an explicit written refund-fee policy", "Integrated waiver evidence, refundable deposits, equipment demand, named units, and operator check-in", "A focused migration path that proves the direct channel before traffic moves"],
  chooseCompetitorIf: ["OTA and reseller distribution is a primary acquisition channel today.", "Gift cards, packages, and Rezdy's channel manager are immediate requirements.", "You want a mature tour platform with a broad global network."], chooseReservKitIf: ["Direct bookings are the priority and you want a published lower fee at scale.", "You prefer Stripe Connect and operational records centered on each booking.", "Waivers, deposits, and equipment readiness are more urgent than OTA expansion.", "You want to stage and test the switch activity by activity."],
  checkpoints: [{ title: "Separate channels", body: "Quantify direct, walk-up, reseller, and OTA bookings before choosing for distribution breadth." }, { title: "Price direct volume", body: "Calculate platform cost using the direct booking subtotal that actually incurs fees." }, { title: "Map resources", body: "Test guide, vehicle, boat, room, and equipment conflicts against real overlapping departures." }, { title: "Verify migration", body: "Keep the current system live until the new booking, payment, message, and check-in path passes." }],
  faqs: [{ title: "Is ReservKit a Rezdy channel-manager replacement?", body: "No. Rezdy advertises a substantially broader reseller and OTA distribution network. ReservKit should be chosen for its current direct-booking and operational workflow, not for equivalent channel breadth." }, { title: "How do current booking fees compare?", body: "Rezdy currently publishes a 3% online booking fee across its listed plans. ReservKit publishes 1.5% on Starter, 1% on Growth, and 0.5% on Pro with a monthly fee cap. Verify both providers' current terms before purchase." }, { title: "Can I evaluate ReservKit before switching?", body: "Yes. The 14-day full-access trial is intended for configuring and testing the first complete flow before selecting a paid plan or moving live traffic." }],
};
export default function RezdyAlternative() { return <ComparisonPage config={config} />; }
